name = "auth"
main = ".dist/index.mjs"
compatibility_date = "2023-07-10"
send_metrics = false

[[ d1_databases ]]
binding = "__D1_BETA__DB"
database_name = "alias-dev"
database_id = "696cb66a-86dd-4aa6-8df4-e1c51533452e"

[build]
command = "pnpm build"

[dev]
port = 8081
